version: "3"
services:
  a2a:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      WEB_HOST_NAME: "0.0.0.0"
      WEB_HOST_PORT: "8080"
      WEB_HOST_TLS: "off"
    ports:
      - 8080:8080
    volumes:
      - ../a2a-demo:/srv
